Repository Anroux11/Potholio, pull requests merged in 2025-07, with the labels that each got.

#50 added the provider for the municipality
  Frontend/package-lock.json
  Frontend/src/providers/municipality-provider/actions.tsx
  Frontend/src/providers/municipality-provider/context.tsx
  Frontend/src/providers/municipality-provider/index.tsx
  Frontend/src/providers/municipality-provider/reducer.tsx
Labels: enhancement

#58 Implemented the ServiceProvider provider
  Frontend/src/providers/serviceProvider-provider/actions.tsx
  Frontend/src/providers/serviceProvider-provider/context.tsx
  Frontend/src/providers/serviceProvider-provider/index.tsx
  Frontend/src/providers/serviceProvider-provider/reducer.tsx
Labels: enhancement

#63 Added the Service Provider List
  Frontend/src/providers/serviceProvider-provider/actions.tsx
  Frontend/src/providers/serviceProvider-provider/context.tsx
  Frontend/src/providers/serviceProvider-provider/index.tsx
  Frontend/src/providers/serviceProvider-provider/reducer.tsx
Labels: enhancement

#69 Moved the login and register inside the auth folder
  Frontend/src/app/(auth)/login/page.tsx
  Frontend/src/app/(auth)/login/style/styles.ts
  Frontend/src/app/(auth)/register/page.tsx
  Frontend/src/app/(auth)/register/style/style.ts
Labels: enhancement

#73 Feature - Added new roles for different users
  Backend/src/Potholio.Application/CrudAppServiceses/Citizens/CitizenAppService.cs
  Backend/src/Potholio.Application/CrudAppServiceses/Citizens/DTo/CitizenRegisterDTo.cs
  Backend/src/Potholio.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/HostRoleAndUserCreator.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
Labels: enhancement

#74 update input on register municipality
  Frontend/src/app/(auth)/register/page.tsx
  Frontend/src/app/(auth)/register/style/style.ts
Labels: enhancement

#75 Update docker-compose.yml
  .github/workflows/docker-compose.yml
Labels: enhancement

#78 edited login messages on login page
  Frontend/src/app/(auth)/login/page.tsx
  Frontend/src/app/citizen/layout.tsx
Labels: enhancement

#82 Feature - Updated database
  Backend/src/Potholio.EntityFrameworkCore/Migrations/.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250716102339_Added_citizenRole.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250716102339_Added_citizenRole.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717055552_UpdatedEntities.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717055552_UpdatedEntities.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717064551_Updated_Incidents.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717064551_Updated_Incidents.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717080017_Updated_Incident.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717080017_Updated_Incident.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717093726_Updated_tables.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717093726_Updated_tables.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250717144747_Updated_municipalityTable.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250718084519_Initial_Create.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250718084519_Initial_Create.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/PotholioDbContextModelSnapshot.cs
  Backend/src/Potholio.EntityFrameworkCore/Potholio.EntityFrameworkCore.csproj
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
  Backend/src/Potholio.Web.Host/appsettings.json
Labels: enhancement

#84 Fixing frontend
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/IncidentAppService.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
  Frontend/src/app/(auth)/register/page.tsx
  Frontend/src/providers/auth-provider/context.tsx
Labels: bug, enhancement

#86 added the techprovider
  Frontend/src/app/layout.tsx
  Frontend/src/components/citizen-components/createIncident.tsx
  Frontend/src/providers/incident-provider/context.tsx
  Frontend/src/providers/technition-providers/actions.tsx
  Frontend/src/providers/technition-providers/context.tsx
  Frontend/src/providers/technition-providers/index.tsx
  Frontend/src/providers/technition-providers/reducer.tsx
  Frontend/src/providers/users-providers/actions.tsx
  Frontend/src/providers/users-providers/context.tsx
  Frontend/src/providers/users-providers/index.tsx
  Frontend/src/providers/users-providers/models.tsx
  Frontend/src/providers/users-providers/reducer.tsx
Labels: enhancement

#87 updated incidentProvider
  Frontend/src/providers/incident-provider/index.tsx
Labels: bug

#89 update the providers with the correct payloads
  Frontend/src/app/layout.tsx
  Frontend/src/components/muncipality-components/add-service-provider.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/incident-provider/context.tsx
  Frontend/src/providers/incident-provider/index.tsx
  Frontend/src/providers/municipality-provider/context.tsx
  Frontend/src/providers/municipality-provider/index.tsx
  Frontend/src/providers/serviceProvider-provider/context.tsx
  Frontend/src/providers/serviceProvider-provider/index.tsx
  Frontend/src/providers/technician-providers/actions.tsx
  Frontend/src/providers/technician-providers/context.tsx
  Frontend/src/providers/technician-providers/index.tsx
  Frontend/src/providers/technician-providers/reducer.tsx
Labels: enhancement

#90 Feature - updated incident create
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/DTo/IncidentDto.cs
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/IIncidentAppService.cs
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/IncidentAppService.cs
  Frontend/src/app/citizen/dashboard/page.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/incident-provider/context.tsx
  Frontend/src/providers/incident-provider/index.tsx
  Frontend/src/utils/axiosInstance.ts
Labels: bug, enhancement

#94 Updated citizen Payload
  Frontend/src/app/citizen/dashboard/page.tsx
Labels: enhancement

#95 moved google api to env
  Frontend/src/components/citizen-components/citizen-map.tsx
Labels: enhancement

#97 Updated full report create
  Frontend/src/app/citizen/dashboard/page.tsx
Labels: enhancement

#100 Feature - updated backend
  Backend/src/Potholio.Core/Domain/Incidents/Incident.cs
  Backend/src/Potholio.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/HostRoleAndUserCreator.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250721110714_DB_Initilize.Designer.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/20250721110714_DB_Initilize.cs
  Backend/src/Potholio.EntityFrameworkCore/Migrations/PotholioDbContextModelSnapshot.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
Labels: bug, enhancement

#101 Feature - updated the getall method
  Backend/src/Potholio.Application/CrudAppServiceses/Addresses/Dto/AddressDto.cs
  Backend/src/Potholio.Application/CrudAppServiceses/Mapper/UserMapProfile.cs
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/IncidentAppService.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
Labels: enhancement

#102 Feature - added municipality name to response
  Backend/src/Potholio.Application/CrudAppServiceses/Reports/IncidentAppService.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
Labels: bug, enhancement

#104 added the admin page for a user to register under a municipality
  Frontend/src/app/(auth)/login/page.tsx
  Frontend/src/app/(auth)/register/page.tsx
  Frontend/src/app/admin/dashboard/page.tsx
  Frontend/src/app/admin/dashboard/style/styles.ts
  Frontend/src/app/admin/layout.tsx
  Frontend/src/app/admin/style/styles.ts
  Frontend/src/app/layout.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/citizen-provider/context.tsx
  Frontend/src/providers/citizen-provider/index.tsx
Labels: enhancement

#105 Mapped inicidents to the municipality dashboard
  Frontend/src/app/citizen/dashboard/page.tsx
  Frontend/src/app/citizen/incidents/page.tsx
  Frontend/src/app/municipality/incidents/page.tsx
  Frontend/src/providers/incident-provider/index.tsx
Labels: enhancement

#106 updated the upload image file
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/admin/dashboard/page.tsx
  Frontend/src/app/citizen/dashboard/page.tsx
  Frontend/src/app/layout.tsx
  Frontend/src/components/muncipality-components/incidents.tsx
  Frontend/src/providers/image-provider/actions.tsx
  Frontend/src/providers/image-provider/context.tsx
  Frontend/src/providers/image-provider/index.tsx
  Frontend/src/providers/image-provider/reducer.tsx
  Frontend/src/utils/supabaseClient.ts
Labels: enhancement

#108 Feature - updated endpoint to update user info
  Backend/Potholio.sln
  Backend/src/Potholio.Application/CrudAppServiceses/Citizens/RegisterAppService.cs
  Backend/src/Potholio.Application/Users/UserAppService.cs
  Backend/src/Potholio.Web.Host/App_Data/Logs/Logs.txt
Labels: enhancement

#112 updated the settings page to update your information
  Frontend/src/app/admin/layout.tsx
  Frontend/src/app/citizen/layout.tsx
  Frontend/src/app/citizen/settings/page.tsx
  Frontend/src/app/municipality/layout.tsx
  Frontend/src/app/serviceProvider/layout.tsx
  Frontend/src/providers/auth-provider/actions.tsx
  Frontend/src/providers/auth-provider/context.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/citizen-provider/index.tsx
Labels: enhancement

#121 Wrapped the HOC on the necessary paths
  Frontend/src/app/admin/layout.tsx
  Frontend/src/app/citizen/layout.tsx
  Frontend/src/app/municipality/layout.tsx
  Frontend/src/app/serviceProvider/layout.tsx
  Frontend/src/hoc/withAuth.tsx
Labels: enhancement

#122 added a readme file for both frontend and backend
  Frontend/README.md
  README.md
Labels: documentation

#124 Integrated AI to interpret Images and write prompts
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/serviceProvider/dashboard/page.tsx
  Frontend/src/app/serviceProvider/gemini/page.tsx
  Frontend/src/app/serviceProvider/gemini/style/styles.ts
  Frontend/src/app/serviceProvider/layout.tsx
  Frontend/src/app/serviceProvider/technicians/page.tsx
  Frontend/src/app/serviceProvider/technicians/style/styles.ts
  Frontend/src/components/Gemini/gemini.tsx
Labels: bug, enhancement

#125 Updated background colour on Response box
  Frontend/src/app/serviceProvider/gemini/style/styles.ts
Labels: enhancement
